### ISSUE TITLE
Build / run unit tests on macOS

### ISSUE THREAD

**Issue by pascalberger** [cake-contrib/Cake.Issues#116]
We should build and run unit tests also on macOS

**Comment by christianbumann** [comment]
@pascalberger Is this related with [this PR](https://github.com/cake-contrib/Cake.Issues/pull/82)?

**Comment by pascalberger** [comment]
@christianbumann #82 was an attempt to get build/test running on macOS, but it was never finished. Parts of it are merged in the meantime

**Comment by christianbumann** [comment]
I will try to find some time to do this task because I have a Mac. I am sure that I'll find the information to get this running....
