### ISSUE TITLE
(Question) Report the issues to an Azure Devops Build (not a the pullrequest)

### ISSUE THREAD

**Issue by janniksam** [cake-contrib/Cake.Issues#164]
I'm sorry, if this isn't the right place to ask this, but I haven't found a better spot for this question.

I would like to know, if there is a built in way to write my warnings and errors I got from the inspectcode result to the Azure Devops Build that is currently running the script.

I could do something like:

```cs
foreach(var issue in issues)
{
	Warning("R#: {0}", issue.MessageText);
}
```

But I would love to get the information "file" and "line" to the build output aswell, so I was wondering, if there is a built in way I can just use.

Thank you in advance!

**Comment by pascalberger** [comment]
There's currently no out of the box functionality to write issues as messages back to the build log.

[Cake.Issues.Recipe](https://cakeissues.net/docs/recipe/overview) has this implemented for AppVeyor but not yet for Azure DevOps (see [here](https://github.com/cake-contrib/Cake.Issues.Recipe/blob/develop/Cake.Issues.Recipe/Content/tasks/buildservers/AzureDevOpsBuildServer.cake#L54)). Should be fairly simple to add there.

The approach you mentioned seems like a reasonable way to implement it. Where do you expect the file and line information? The [IIssue interface](https://cakeissues.net/api/Cake.Issues/IIssue/#Properties) provides an [AffectedFileRelativePath](https://cakeissues.net/api/Cake.Issues/IIssue/BF0CD6F1) and [Line](https://cakeissues.net/api/Cake.Issues/IIssue/F2A42E89) property which could additionally be passed to the warning. Would this work for you?

**Comment by janniksam** [comment]
Thank you for the info. 👍 

I will try to do it like this, it _could_ work:

Warning("#vso[task.logissue type=warning;sourcepath={0};linenumber={1};columnnumber=1]R# - {2}", issue.AffectedFileRelativePath, issue.Line, issue.MessageText);

**Comment by pascalberger** [comment]
Please let me know if it works for you. I would be happy to add this to Cake.Issues.Recipe or maybe even create a new addin which provides this functionality, similar to the AppVeyor addin.

**Comment by janniksam** [comment]
Unfortunately it does not work. I think, the Warning() is causing the trouble. I am pretty sure, it was working with Write-Host in a powershell script. I will continue my research tomorrow.

**Comment by pascalberger** [comment]
There's a [WriteWarning command](https://cakebuild.net/api/Cake.Common.Build.TFBuild/ITFBuildCommands/37582CA4) which should work (internally it uses the `task.logissue` command). You can call it like this:

```
TFBuild.Commands.WriteWarning(
    issue.MessageText,
    new TFBuildMessageData
    {
        SourcePath = issue.AffectedFileRelativePath,
        Line = issue.Line
    });
```

**Comment by janniksam** [comment]
Awesome finding! 👍 
I will test that out tomorow and give you my feedback.

Maybe we should, to have a clean easy to use possibilty, add a wrapper for it in Cake.Issues anyways.

**Comment by pascalberger** [comment]
I've implemented reporting of issues to Azure Pipelines using the above approach in Cake.Issues.Recipe with [version 0.3.2](https://cakeissues.net/docs/recipe/release-notes#april-15-2020). See [here](https://dev.azure.com/cake-contrib/Cake.Issues.Recipe/_build/results?buildId=3082&view=results) for an example build.

**Comment by janniksam** [comment]
Thank you, this is resolved 👍
