### ISSUE TITLE
Add possibility to add arbitrary values to an issue

### ISSUE THREAD

**Issue by pascalberger** [cake-contrib/Cake.Issues#215]
Specific issue providers might have additional information for which no equivalent doesn't exist on `IIssue`. For these kind of information it would be useful to have a property which can hold an additional list of key / value pairs.

**Comment by janniksam** [comment]
So, I looked into it for a couple of minutes now...

What datatype do we want the "AdditionalInformation" property to have. I mean, I can start with `IReadOnlyDictionary<string, object>`, but I am not sure about this, especially regarding the serializability of the issues. 

What do you think - Should we add a new class "AdditionalIssueInformation", that holds a "Key" and a "Value" property instead?

**Comment by pascalberger** [comment]
@janniksam Sorry, somehow missed this comment.

Serializability is a requirement. How about using `string` instead of `object` for value? This would solve serialization form a Cake.Issues point of view and makes it a responsibility of the caller.

I currently don't see any advantages of introductin a specific class for holding the values compared to using an dictionary.

**Comment by janniksam** [comment]
So what you're saying is that the type Dictionary<string,string> is fine?
In the past I heard, that in general dictionaries aren't that great for serialization.

**Comment by pascalberger** [comment]
> So, what you're saying is that the type Dictionary<string,string> is fine?

I **think** it should be fine 😃 Otherwise we'll find out, since there are aliases & test cases for serializing and deserializing of issues (using [litJson](https://github.com/LitJSON/litjson))

**Comment by janniksam** [comment]
Okay, in that case I already started last week to add the dictionary. I will continue the work on it this weekend. :)
