### ISSUE TITLE
Migrate to .NET Core

### ISSUE THREAD

**Issue by pascalberger** [cake-contrib/Cake.Issues#4]
Addin should support .NET Core and Cake CoreCLR runner

**Comment by t-johnson** [comment]
I will take this on.  standard 1.6 or standard 2.0?

**Comment by pascalberger** [comment]
@t-johnson That would be great!

Stuff which needs to be done:

- Converted solution to Visual Studio 2017
- Add .NET Standard 1.6 target
- Build against latest Cake
- Use Visual Studio 2017 AppVeyor image

@RLittlesII @gep13 Since you have already migrated some other plugins, have I forgotten something?

**Comment by gep13** [comment]
If I remember correctly, you need to bump 4.5 to 4.6, which will need a change in the nuspec file as well.

**Comment by gep13** [comment]
On phone just now, but if you find one of @RLittlesII PRs for one of the other addins, that you be a good place to start.

**Comment by pascalberger** [comment]
@gep13 Thanks. Sure, building against latest Cake requires bumping to .NET 4.6. Also linked to some PRs migrating other addins to .NET Core as guidelines.

**Comment by RLittlesII** [comment]
@pascalberger seems to be the correct steps.  I think the tricky part is the new csproject format and any odd dependencies.  If you want me to look at PR’s let me know.
I might even recommend bumping to net46 in a separate commit as that has caused me some headache.

**Comment by t-johnson** [comment]
thanks, this is pretty clear on whats expected.

**Comment by pascalberger** [comment]
Cake 0.22.0 should actually be high enough to support .NET Core. There's therefore no need to build against a newer Cake version. .NET Framework 4.6 is also already targetted. I updated the list above.
