### ISSUE TITLE
Support MSBuildStructuredLog

### ISSUE THREAD

**Issue by pascalberger** [cake-contrib/Cake.Issues#404]
Add support for formats from [MSBuildStructuredLog](https://github.com/KirillOsenkov/MSBuildStructuredLog) (*.buildlog, *.xml)

**Comment by KirillOsenkov** [comment]
Should we close this? I want to deprecate the .buildlog format and .xml format, they haven’t evolved since 2017.

**Comment by pascalberger** [comment]
Sure, makes sense to close this since they no longer are supported
